# alt: added some comments at the top of the file
# multi-line that is

name: PR-checklist

on:
  pull_request_target:
    types: [opened, edited]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  add-checklist-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-checklist
          only_create: true
          message: |
            ## PR Checklist
            :information_source: This checklist serves as a reminder of things we care about for both the author and the reviewer.

            - [ ] test
